

def script_generator(x1, x2, *args):x

    data = [
    f"#############################################################\n",
    f"## JOB DESCRIPTION                                         ##\n",
    f"#############################################################\n",
    f"\n",
    f"# SMD off NH3 in AmtB, k=5\n",
    f"\n",
    f"#############################################################\n",
    f"## ADJUSTABLE PARAMETERS                                   ##\n",
    f"#############################################################\n",
    f"\n",
    f"structure          Step5-Input.psf\n",
    f"coordinates        p1315-Step5-Input.pdb.pdb\n",
    f"\n",
    f"set temperature    310\n",
    f"set outputname     zzout-Step5-Output\n",
    f"\n",
    f"#set inputname      ../common/AmtB-equil\n",
    f"\n",
    f"#binCoordinates $inputname.restart.coor\n",
    f"#binVelocities $inputname.restart.vel\n",
    f"#extendedSystem $inputname.restart.xsc\n",
    f"\n",
    f"#proc get_first_ts { xscfile } {\n",
    f"#  set fd [open $xscfile r]\n",
    f"#  gets $fd\n",
    f"#  gets $fd\n",
    f"#  gets $fd line\n",
    f"#  set ts [lindex $line 0]\n",
    f"#  close $fd\n",
    f"#  return $ts\n",
    f"#}\n",
    f"\n",
    f"#set firsttime [get_first_ts $inputname.restart.xsc]\n",
    f"\n",
    f"firsttimestep 0\n",
    f"\n",
    f"#############################################################\n",
    f"## SIMULATION PARAMETERS                                   ##\n",
    f"#############################################################\n",
    f"\n",
    f"# Input\n",
    f"paraTypeCharmm	    on\n",
    f"parameters          paramfiles/par_all27_prot_lipid_cmap.inp\n",
    f"parameters          paramfiles/toppar_amines.str\n",
    f"parameters	    		paramfiles/par_all36_lipid.prm\n",
    f"parameters              toppar/par_all36m_prot.prm\n",
    f"parameters              toppar/par_all36_na.prm\n",
    f"parameters              toppar/par_all36_carb.prm\n",
    f"parameters              toppar/par_all36_lipid.prm\n",
    f"parameters              toppar/par_all36_cgenff.prm\n",
    f"parameters              toppar/par_interface.prm\n",
    f"parameters              toppar/toppar_all36_moreions.str\n",
    f"parameters              toppar/toppar_all36_nano_lig.str\n",
    f"parameters              toppar/toppar_all36_nano_lig_patch.str\n",
    f"parameters              toppar/toppar_all36_synthetic_polymer.str\n",
    f"parameters              toppar/toppar_all36_synthetic_polymer_patch.str\n",
    f"parameters              toppar/toppar_all36_polymer_solvent.str\n",
    f"parameters              toppar/toppar_water_ions.str\n",
    f"parameters              toppar/toppar_dum_noble_gases.str\n",
    f"parameters              toppar/toppar_ions_won.str\n",
    f"parameters              toppar/cam.str\n",
    f"parameters              toppar/toppar_all36_prot_arg0.str\n",
    f"parameters              toppar/toppar_all36_prot_c36m_d_aminoacids.str\n",
    f"parameters              toppar/toppar_all36_prot_fluoro_alkanes.str\n",
    f"parameters              toppar/toppar_all36_prot_heme.str\n",
    f"parameters              toppar/toppar_all36_prot_na_combined.str\n",
    f"parameters              toppar/toppar_all36_prot_retinol.str\n",
    f"parameters              toppar/toppar_all36_prot_model.str\n",
    f"parameters              toppar/toppar_all36_prot_modify_res.str\n",
    f"parameters              toppar/toppar_all36_na_nad_ppi.str\n",
    f"parameters              toppar/toppar_all36_na_rna_modified.str\n",
    f"parameters              toppar/toppar_all36_lipid_sphingo.str\n",
    f"parameters              toppar/toppar_all36_lipid_archaeal.str\n",
    f"parameters              toppar/toppar_all36_lipid_bacterial.str\n",
    f"parameters              toppar/toppar_all36_lipid_cardiolipin.str\n",
    f"parameters              toppar/toppar_all36_lipid_cholesterol.str\n",
    f"parameters              toppar/toppar_all36_lipid_dag.str\n",
    f"parameters              toppar/toppar_all36_lipid_inositol.str\n",
    f"parameters              toppar/toppar_all36_lipid_lnp.str\n",
    f"parameters              toppar/toppar_all36_lipid_lps.str\n",
    f"parameters              toppar/toppar_all36_lipid_mycobacterial.str\n",
    f"parameters              toppar/toppar_all36_lipid_miscellaneous.str\n",
    f"parameters              toppar/toppar_all36_lipid_model.str\n",
    f"parameters              toppar/toppar_all36_lipid_prot.str\n",
    f"parameters              toppar/toppar_all36_lipid_tag.str\n",
    f"parameters              toppar/toppar_all36_lipid_yeast.str\n",
    f"parameters              toppar/toppar_all36_lipid_hmmm.str\n",
    f"parameters              toppar/toppar_all36_lipid_detergent.str\n",
    f"parameters              toppar/toppar_all36_lipid_ether.str\n",
    f"parameters              toppar/toppar_all36_carb_glycolipid.str\n",
    f"parameters              toppar/toppar_all36_carb_glycopeptide.str\n",
    f"parameters              toppar/toppar_all36_carb_imlab.str\n",
    f"parameters              toppar/toppar_all36_label_spin.str\n",
    f"parameters              toppar/toppar_all36_label_fluorophore.str\n",
    f"temperature         $temperature\n",
    f"\n",
    f"\n",
    f"# Force-Field Parameters\n",
    f"exclude             scaled1-4\n",
    f"1-4scaling          1.0\n",
    f"cutoff              12.\n",
    f"switching           on\n",
    f"switchdist          10.\n",
    f"pairlistdist        13.5\n",
f"\n",
f"\n",
    f"# Integrator Parameters\n",
    f"timestep           0.1  ;# 2fs/step (only if needed to finish quickly)\n",
    f"rigidBonds         water  ;# needed for 2fs steps\n",
    f"nonbondedFreq       2\n",
    f"fullElectFrequency  4  \n",
    f"stepspercycle       20\n",
f"\n",
f"\n",
    f"# Constant Temperature Control\n",
    f"langevin            on    ;# do langevin dynamicsgmail.google.com\n",
    f"langevinDamping     1     ;# damping coefficient (gamma) of 5/ps\n",
    f"langevinTemp        $temperature\n",
    f"langevinHydrogen    off    ;# don't couple langevin bath to hydrogens\n",
f"\n",
f"\n",
    f"# Periodic Boundary Conditions\n",
    f"cellBasisVector1    77    0.   0.\n",
    f"cellBasisVector2     0.   77.5   0.\n",
    f"cellBasisVector3     0.    0    91\n",
    f"cellOrigin          -8.698963 -8.058146 -5.344311\n",
f"\n",
    f"wrapAll             on\n",
f"\n",
f"\n",
    f"# PME (for full-system periodic electrostatics)\n",
    f"PME                 yes\n",
    f"PMEGridSpacing      1.0\n",
f"\n",
    f"# Constant Pressure Control (variable volume)\n",
    f"useGroupPressure      no ;# needed for rigidBonds\n",
    f"useFlexibleCell       no\n",
    f"useConstantArea       no\n",
f"\n",
    f"langevinPiston        on\n",
    f"langevinPistonTarget  1.01325 ;#  in bar -> 1 atm\n",
    f"langevinPistonPeriod  100.\n",
    f"langevinPistonDecay   50.\n",
    f"langevinPistonTemp    $temperature\n",
f"\n",
f"\n",
    f"# Output\n",
    f"outputName          $outputname\n",
f"\n",
    f"restartfreq         1000     ;# 1000steps = every 1ps\n",
    f"dcdfreq             1000\n",
    f"xstFreq             1000\n",
    f"outputEnergies      100\n",
    f"outputPressure      100\n",
    f"#forceDCDfreq				1000\n",
    f"#forceDCDfile 			$outputname.forcedcd.dcd\n",
f"\n",
    f"#############################################################\n",
    f"## EXTRA PARAMETERS                                        ##\n",
    f"#############################################################\n",
f"\n",
    f"colvars              on\n",
    f"colvarsConfig        restrain.in\n",
f"\n",
    f"constraints on\n",
    f"consexp 2\n",
    f"consref rest6.ref\n",
    f"conskfile rest6.ref\n",
    f"conskcol O\n",
    f"selectConstraints on\n",
    f"selectConstrX off\n",
    f"selectConstrY off\n",
    f"selectConstrZ on\n",
f"\n",
    f"SMD off\n",
    f"SMDFile smd01.ref\n",
    f"SMDk 0  \n",
    f"SMDVel .00000   ;# 10 A/ns = .01 A/ps = .00001 A/fs\n",
    f"SMDDir {np.cos(x1)} -0.2316291938381645 0.89926821863939471 # SMD+z\n",
    f"SMDOutputFreq 1000\n",
f"\n",
    f"#############################################################\n",
    f"## EXECUTION SCRIPT                                        ##\n",
    f"#############################################################\n",
f"\n",
    f"# Minimization\n",
    f"minimize            15000\n",
    f"reinitvels          $temperature\n",
f"\n",
    f"run 30000000 ;#"\n",
f"\n"
    ]
    with open(filename) do f:
        f.writelines(data)